name: N267 Weekly Missions CI

on:
  schedule:
    # Runs every Monday at 03:00 UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  build-and-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm -w install

      - name: Build
        run: pnpm -w build

      - name: Create status artifact file
        if: always()
        run: echo archived > status

      - name: Archive status artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: status
          path: status
