
# GNEW • N267
# CI/CD pipeline para validar generación de misiones semanales
# - Ejecuta pruebas unitarias del módulo feedback→misiones (N266).
name: Weekly Missions CI (archived)
on: { workflow_dispatch: {} }
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Archived. See docs/_imported/.github-workflows-n267-weekly-missions-ci.yml.md"
