groups:
  - name: realtime-slo
    rules:
      - alert: RealtimeP95High
        expr: histogram_quantile(0.95, sum(rate(rt_broadcast_latency_seconds_bucket[5m])) by (le)) > 0.3
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "P95 de broadcast supera 300ms"
          description: "Verifica NATS, colas y CPU."
      - alert: RealtimeDrops
        expr: rate(rt_dropped_messages_total[5m]) > 1
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Backpressure alto en realtime"
# Archived original content moved to docs/_imported/infra-alerts-realtime.yaml.md
