/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  AddressLike,
  BaseContract,
  ContractTransactionResponse,
} from "ethers";

export interface GnewGovToken extends BaseContract {
  delegate(delegatee: AddressLike): Promise<ContractTransactionResponse>;
}
