/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  AddressLike,
  BaseContract,
  BigNumberish,
  BytesLike,
  ContractTransactionResponse,
} from "ethers";

export interface GnewGovernor extends BaseContract {
  propose(
    targets: AddressLike[],
    values: BigNumberish[],
    calldatas: BytesLike[],
    description: string
  ): Promise<ContractTransactionResponse>;

  castVote(
    proposalId: BigNumberish,
    support: BigNumberish
  ): Promise<ContractTransactionResponse>;

  queue(
    targets: AddressLike[],
    values: BigNumberish[],
    calldatas: BytesLike[],
    descriptionHash: BytesLike
  ): Promise<ContractTransactionResponse>;

  execute(
    targets: AddressLike[],
    values: BigNumberish[],
    calldatas: BytesLike[],
    descriptionHash: BytesLike
  ): Promise<ContractTransactionResponse>;
}
