[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib","../../contracts/lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
via_ir = true

[fmt]
line_length = 120
tab_width = 4

[profile.ci]
optimizer_runs = 10

