openapi: 3.1.0
info:
  title: GNEW Public API (Quickstarts)
  version: 0.1.0
servers:
  - url: https://api.gnew.example.com
paths:
  /auth/api-key/verify:
    get:
      summary: Verify API Key
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-GNEW-API-KEY
# Note: original contaminated content archived at docs/_imported/gnew-devrel-quickstarts-shared-openapi.yaml.md
