repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        args: [--baseline-path, .gitleaks-baseline.json, --redact]
        stages: [commit, push]
  - repo: local
    hooks:
      - id: forbid-latest-tag
        name: Forbid latest tag in k8s manifests
        language: system
        entry: bash
        args:
          - -c
          - |
            grep -R "image: .*:latest" -n apps infra || echo OK
        pass_filenames: false
      - id: lockfiles-present
        name: Ensure lockfiles present
        language: system
        entry: bash
        args:
          - -c
          - |
            test -f pnpm-lock.yaml || test -f package-lock.json || test -f poetry.lock || test -f requirements.txt || (echo "Falta lockfile" && exit 1)
        pass_filenames: false
