
name: M18 FinOps Gas

on:
  pull_request:
    paths:
      - "services/finops/**"
      - "apps/dao-web/pages/api/finops/**"
      - "tests/finops/test_m18_gas.spec.ts"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      anvil:
        image: ghcr.io/foundry-rs/anvil
        ports:
          - 8545:8545
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Instalar dependencias
        run: npm ci
      - name: Ejecutar tests M18
        run: npx mocha tests/finops/test_m18_gas.spec.ts


