
name: M8 Fraud Detection

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  fraud-detector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test -- tests/fraud/test_m8_fraud_detector.test.ts


