
name: M9 Key & DID Manager

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-m9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test -- tests/identity/test_m9_key_did_manager.test.ts


