
# =============================================================================
# GNEW • N260 — Kubernetes Policy as Code (OPA Gatekeeper)
apiVersion: v1
kind: List
metadata:
  annotations:
    note: Original content archived at docs/_imported/infra-k8s-policy-n260-gatekeeper-constraints.yaml.md
items: []
#  - Bloquear volúmenes hostPath y seccomp no restringido

# Aplicación: kubectl apply -f n260-gatekeeper-constraints.yaml
