version: "3.9" 
services: 
  gnew-exporter: 
    build: 
      context: .. 
      dockerfile: ./apps/observability.Dockerfile 
    image: gnew/observability:0.1.0 
    env_file: 
      - ../apps/observability/.env 
    ports: 
      - "9108:9108" 
    restart: unless-stopped 
  prometheus: 
    image: prom/prometheus:v2.54.0 
    command: ["--config.file=/etc/prometheus/prometheus.yml", 
"--web.enable-lifecycle"] 
    volumes: 
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro 
      - ./prometheus/rules:/etc/prometheus/rules:ro 
      - promdata:/prometheus 
    ports: 
      - "9090:9090" 
    restart: unless-stopped 
  alertmanager: 
    image: prom/alertmanager:v0.27.0 
    volumes: 
      - 
./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro 
    ports: 
      - "9093:9093" 
    restart: unless-stopped 
  grafana: 
    image: grafana/grafana:11.1.0 
    environment: 
      - GF_AUTH_ANONYMOUS_ENABLED=true 
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer 
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning 
      - ./grafana/dashboards:/var/lib/grafana/dashboards 
    ports: 
      - "3000:3000" 
    restart: unless-stopped 
volumes: 
  promdata: {} 
 
