openapi: 3.1.0 
info: { title: GNEW Jurisdiction API, version: 1.0.0 } 
paths: 
  /v1/jx/catalog: 
    get: { summary: Versión activa y cobertura, responses: { "200": { 
description: OK } } } 
  /v1/jx/{countryCode}/effective: 
    get: 
      summary: Reglas efectivas por país 
      parameters: 
        - in: path; name: countryCode; required: true; schema: { type: 
string, minLength: 2, maxLength: 2 } 
        - in: query; name: productType; schema: { type: string } 
      responses: { "200": { description: OK } } 
  /v1/jx/resolve: 
    post: 
      summary: Resolver obligaciones (impuestos/KYC/límites) 
      requestBody: { required: true } 
      responses: { "200": { description: OK } } 
 
