route:
  receiver: pagerduty
  group_by: ["alertname","team"]
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 2h
  routes:
    - matchers: [severity="critical"]
      receiver: pagerduty
    - matchers: [team="security"]
      receiver: sec-slack

receivers:
  - name: pagerduty
    pagerduty_configs:
      - routing_key: ${PAGERDUTY_ROUTING_KEY}
        severity: "{{ .CommonLabels.severity | default \"error\" }}"
  - name: sec-slack
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL}
        channel: "#sec-alerts"
        title: "{{ .CommonAnnotations.summary }}"
        text: "{{ .CommonAnnotations.description }}"

