image:
  repository: gnew/did-service
  tag: v0.1.0

env:
  GNEW_RPC_URL: https://rpc.gnew.example
  GNEW_DID_REGISTRY: "0xRegistryAddress"
  REGISTRAR_PRIVATE_KEY: "vault://kv/did/registrar"
  IPFS_NODE_URL: http://ipfs:5001
  IPFS_GATEWAY: https://ipfs.io/ipfs/

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  hosts:
    - did.api.gnew.example
