
namespace: backup

labels:
  project: GNEW
  component: backup
  environment: prod
  managed-by: helm

provider:
  type: aws

common:
  bucket: gnew-prod-backups
  prefix: k8s/cluster-1
  region: eu-west-1
  snapshots: false
  defaultTTL: 720h
  schedules:
    nightly: "0 3 * * *"
    hourly: "0 * * * *"

image:
  repository: velero/velero
  tag: v1.14.2
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

credentials:
  useSecret: true
  existingSecret: velero-credentials

metrics:
  enabled: true

schedules:
  nightly:
    schedule: "0 3 * * *"
  hourly:
    schedule: "0 * * * *"

