image: 
  repository: gnew/reputation-api 
  tag: v0.1.0 
env: 
  REP_DATA_DIR: /data/reputation 
  REPUTATION_REGISTRY: "0xReputationRootRegistry" 
  GNEW_RPC_URL: https://rpc.gnew.example 
ingress: 
  enabled: true 
  hosts: [ "reputation.api.gnew.example" ] 
resources: 
  requests: { cpu: "100m", memory: "256Mi" } 
  limits: { cpu: "500m", memory: "512Mi" } 
