image:
  repository: gnew/reputation-service
  tag: v0.1.0

env:
  GNEW_RPC_URL: https://rpc.gnew.example
  REPUTATION_REGISTRY: "0xReputationRootRegistry"
  REP_UPDATER_KEY: "vault://kv/reputation/updater"

ingress:
  enabled: true
  hosts:
    - rep.api.gnew.example

cron:
  schedule: "0 2 * * *" # daily at 02:00 UTC
  args:
    - "--config=/app/config/formula.v1.yaml"
    - "--epoch=$(date +%Y%m%d)"
    - "--out=/data/out"

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"
