[profile.default] 
src = "src" 
out = "out" 
test = "test" 
libs = ["lib"] 
solc = "0.8.24"
evm_version = "paris" 
optimizer = true 
optimizer_runs = 200 
fs_permissions = [{ access = "read", path = "./"}] 
# Remappings para usar OZ desde node_modules y forge-std desde lib 
remappings = [ 
"@openzeppelin/=../../node_modules/@openzeppelin/", 
"forge-std/=lib/forge-std/src/" 
] 
