
# M12: Seguridad de Cadena de Suministro
# Generación automática de SBOM con CycloneDX

name: Generate SBOM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Generar SBOM (CycloneDX)
        run: npx @cyclonedx/cyclonedx-npm --output-file sbom.json

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json


