global: 
scrape_interval: 15s 
evaluation_interval: 15s 
rule_files: - /etc/prometheus/rules/recording-rules.yml - /etc/prometheus/rules/alerting-rules.yml 
scrape_configs: - job_name: gnew-exporter 
static_configs: - targets: ["gnew-exporter:9108"] 
# Opcional: si tienes Blockscout propio con /metrics 
# - job_name: blockscout 
#   static_configs: 
#     - targets: ["blockscout:4000"] 
alerting: 
  alertmanagers: 
    - static_configs: 
        - targets: ["alertmanager:9093"] 
 
