version: "3.9"
services:
  pdp:
    build: .
    ports:
      - "8090:8090"
    environment:
      PDP_API: http://pdp:8090
      OPA_URL: http://opa:8181
      POLICY_REGISTRY_URL: http://registry:8089
      POLICY_VERSION: v1.0.0
    depends_on:
      - opa
      - registry
  opa:
    image: openpolicyagent/opa:0.66.0-rootless
    command: ["run","--server","--config-file=/config/config.yaml"]
    ports:
      - "8181:8181"
    volumes:
      - ./opa/config.yaml:/config/config.yaml:ro
  registry:
    build: ../policy-registry-svc
    ports:
      - "8089:8089"
    environment:
      BUNDLES_DIR: /bundles
    volumes:
      - ../../bundles:/bundles:ro

# Note: original contaminated file archived at docs/_imported/apps-pdp-svc-docker-compose.yaml.md
