name: breach-svc
on:
  push:
    paths:
      - "apps/breach-svc/**"
      - "packages/schemas/openapi/breach.yml"
      - "apps/breach-svc/config/**"
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint --workspaces
      - run: npm test --workspaces
      - name: Validate OpenAPI schema
        run: npx swagger-cli validate packages/schemas/openapi/breach.yml
      - run: npm run build -w apps/breach-svc

