name: Change Approval Gate
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  cab-gate:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CAB gate stub; ver docs/_imported/change-approval-gate.yml.md"
