name: chaos-redteam
on:
  schedule:
    - cron: '0 2 * * 2,5'
  workflow_dispatch: {}
jobs:
  archived:
    runs-on: ubuntu-latest
    steps:
      - name: Archived original workflow
        run: echo "See docs/_imported/chaos-redteam.yml.md for the archived content"
