name: ci 
on: 
push: 
branches: [main, develop] 
pull_request: 
jobs: 
  build-test: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4 
 
      - name: Setup pnpm 
        uses: pnpm/action-setup@v4 
        with: 
          version: 9 
 
      - name: Setup Node 
        uses: actions/setup-node@v4 
        with: 
          node-version: 20 
          cache: "pnpm" 
 
      - name: Install deps 
        run: pnpm install --frozen-lockfile 
 
      - name: Setup Foundry 
        uses: foundry-rs/foundry-toolchain@v1 
        with: 
          version: nightly 
 
      - name: Lint 
        run: pnpm lint 
 
      - name: Compile contracts (Hardhat) 
        run: pnpm contracts:compile 
 
      - name: Tests (Hardhat) 
        run: pnpm test:contracts:hh 
 
      - name: Tests (Foundry) 
        run: pnpm test:contracts:forge 
 
      - name: Coverage (Solidity) 
        run: pnpm coverage 
 
