name: Deploy Strategy
on:
  workflow_dispatch:
    inputs:
      service:
        description: "Servicio"
        type: string
        required: true
      environment:
        description: "Entorno (dev|staging|prod)"
        type: choice
        options: [dev, staging, prod]
        required: true
        default: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm -w install --frozen-lockfile
      - name: Build service
        run: pnpm --filter "${{ inputs.service }}" build
      - name: Deploy service
        run: pnpm --filter "${{ inputs.service }}" deploy:${{ inputs.environment }}
