name: Deploy Canary (ai-coordinator)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Nuevo tag de imagen"
        required: true

jobs:
  update-image-and-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump image tag
        run: |
          sed -i "s#ghcr.io/gnew/ai-coordinator:.*#ghcr.io/gnew/ai-coordinator:${{ github.event.inputs.image_tag }}#g" k8s/services/ai-coordinator/deployment-stable.yaml
      # - uses: azure/setup-kubectl@v4
      # - run: kubectl apply -n gnew -f k8s/services/ai-coordinator/deployment-stable.yaml
      # - run: kubectl apply -n gnew -f k8s/services/ai-coordinator/canary.yaml
