name: Dependency Policy (OSV/License)

on:
  pull_request:
    paths:
      - '**/package.json'
      - '**/pnpm-lock.yaml'
      - '**/requirements.txt'
      - '**/Dockerfile'
  push:
    branches: [ main ]
    paths:
      - '**/package.json'
      - '**/pnpm-lock.yaml'
      - '**/requirements.txt'
      - '**/Dockerfile'

jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps (root only)
        run: pnpm install --frozen-lockfile

      - name: Install OSV-Scanner
        run: |
          curl -sSfL https://raw.githubusercontent.com/google/osv-scanner/main/scripts/install.sh | sudo sh -s -- -b /usr/local/bin
          osv-scanner --version

      - name: OSV Scan (recursive)
        run: |
          osv-scanner -r . --format json > /tmp/osv.json || true
          if jq -e '.results | map(select(.packages != null)) | length > 0' /tmp/osv.json > /dev/null; then
            echo "Vulnerabilidades detectadas por OSV";
            jq -r '.results[] | select(.packages != null) | .packages[]?.package.name' /tmp/osv.json | sort -u;
            exit 1;
          fi

      - name: License check (deny GPL)
        run: |
          pnpm dlx license-checker --production --json > /tmp/licenses.json || true
          if jq -r 'to_entries[] | select(.value.licenses|test("GPL")) | .key' /tmp/licenses.json | grep -q "."; then
            echo "Licencia GPL detectada";
            jq -r 'to_entries[] | select(.value.licenses|test("GPL")) | "- \(.key): \(.value.licenses)"' /tmp/licenses.json;
            exit 1;
          fi
