name: DR Verify (Quarterly)

on:
  schedule:
    - cron: "0 3 1 */3 *"
  workflow_dispatch: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: DR verification (stub)
        run: echo "DR verification workflow stub; see docs/_imported/dr-verify.yml.md"
