name: dsar-svc 
on: 
  push: { paths: ["apps/dsar-svc/**", "packages/dsar-connectors/**", 
"packages/schemas/openapi/dsar.yml"] } 
  pull_request: { branches: [ main ] } 
jobs: 
  build-test: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4 
      - uses: actions/setup-node@v4 
        with: { node-version: 20 } 
      - run: npm ci 
      - run: npm run lint --workspaces 
      - run: npm test --workspaces 
      - run: syft packages dir:. -o spdx-json=sbom-dsar.json || true 
      - run: npx swagger-cli validate 
packages/schemas/openapi/dsar.yml 
      - run: npm run build -w apps/dsar-svc 
  deploy: 
    needs: build-test 
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest 
    permissions: { id-token: write, contents: read } 
    steps: 
      - uses: actions/checkout@v4 
      - name: Auth OIDC 
        run: echo "auth" 
      - name: Deploy 
        run: ./infra/deploy-dsar.sh 
 
 
Pruebas (unit) 
