name: esign-svc 
on: 
  push: 
    paths: 
      - "apps/esign-svc/**" 
      - "apps/web/app/sign/**" 
      - "packages/schemas/openapi/esign.yml" 
      - "apps/esign-svc/config/templates/**" 
  pull_request: { branches: [ main] } 
jobs: 
  build-test: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4 
      - uses: actions/setup-node@v4 
        with: { node-version: 20 } 
      - run: npm ci 
      - run: npm run lint --workspaces 
      - run: npm test --workspaces 
      - run: npx swagger-cli validate 
packages/schemas/openapi/esign.yml 
      - run: npm run build -w apps/esign-svc 
  deploy: 
    needs: build-test 
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest 
    permissions: { id-token: write, contents: read } 
    steps: 
      - uses: actions/checkout@v4 
      - name: Deploy 
        run: ./infra/deploy-esign.sh 
 
