name: Gamification CI

on:
  push:
    paths:
      - 'services/gamification/**'
  pull_request:
    paths:
      - 'services/gamification/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Gamification CI stub; ver docs/_imported/gamification-ci.yml.md"
