name: help-center-ci
on:
  pull_request:
    paths: ["apps/web/content/help/**","apps/web/src/modules/help/**","services/helpdesk/**","tools/**"]
  push:
    branches: [main]
    paths: ["apps/web/content/help/**","services/helpdesk/**","tools/**"]
jobs:
  archived:
    runs-on: ubuntu-latest
    steps:
      - name: Archived original workflow
        run: echo "See docs/_imported/help-center-ci.yml.md for the archived content"
