name: Mobile CI

on:
  pull_request:
    paths: ["apps/mobile/**", ".github/workflows/mobile-ci.yml"]
  push:
    branches: [main]
    paths: ["apps/mobile/**"]

jobs:
  android-detox:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Mobile CI stub; ver docs/_imported/mobile-ci.yml.md"
