name: P13n CI

on:
  push:
    paths:
      - 'services/p13n/**'
  pull_request:
    paths:
      - 'services/p13n/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "P13n CI stub; ver docs/_imported/p13n-ci.yml.md"
