name: Release Train (weekly)
on:
  schedule:
    - cron: "0 8 * * MON"
  workflow_dispatch: {}
jobs:
  cut-train:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release train stub; ver docs/_imported/release-train.yml.md"
