name: Verify Supply Chain (reusable)
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      expected_identity:
        required: true
        type: string
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: sigstore/cosign-installer@v3
        with:
          cosign-release: v2.2.4
      - name: cosign verify (OIDC identity + Rekor)
        run: |
          cosign verify "${{ inputs.image }}" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --certificate-identity "${{ inputs.expected_identity }}" \
            --rekor-url https://rekor.sigstore.dev
      - name: verify SBOM attestation (spdx)
        run: |
          cosign verify-attestation "${{ inputs.image }}" \
            --type spdx \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --certificate-identity "${{ inputs.expected_identity }}"
