name: Rollback (1-click)
on:
  workflow_dispatch:
    inputs:
      app:
        description: "ArgoCD app"
        required: true
        type: string
      revision:
        description: "Revision index (0=previous)"
        required: false
        type: number
        default: 0
jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rollback stub; ver docs/_imported/rollback.yml.md"
