name: sc-security
on:
  pull_request:
    paths:
      - "contracts/**"
  push:
    branches: [ main ]
    paths:
      - "contracts/**"
jobs:
  archived:
    runs-on: ubuntu-latest
    steps:
      - name: Archived original workflow
        run: echo "See docs/_imported/sc-security.yml.md for the archived content"
