name: Secure Scans

on:
  pull_request:
  push:
    branches: [main]
name: secure-scans

on:
  push:
    branches: [main]
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --baseline-path .gitleaks-baseline.json --redact --no-banner
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_ENABLE_SUMMARY: "true"
        with:
          args: detect --no-banner --redact
