name: Support Bot CI

on:
  push:
    paths:
      - 'services/support-bot/**'
  pull_request:
    paths:
      - 'services/support-bot/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Support Bot CI stub; ver docs/_imported/support-bot-ci.yml.md"
